# Generated by Django 5.2.3 on 2025-09-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0002_alter_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User',
            new_name='user',
        ),
    ]
