# Generated by Django 5.2.3 on 2025-09-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0003_rename_user_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='score',
            new_name='rating',
        ),
    ]
