# Generated by Django 5.2.3 on 2025-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0004_rename_score_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
