# Generated by Django 5.2.3 on 2025-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0005_comment_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
