# Generated by Django 5.2.3 on 2025-09-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok_app', '0006_alter_comment_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_email',
        ),
    ]
